### ISSUE TITLE
多签钱包改进建议

### ISSUE THREAD

**Issue by Qihaibiao** [newtonproject/MultiSignatureWallet#1]
多签钱包测试完毕。需要超过半多数人控制资金流的基本功能实现良好。但操作过程复杂，建议如下：

1、0x钱包地址不方便记忆。建议改进翻译为NEW182地址。方便人的记忆，才不会搞错钱包。

2、从合约地址经多签后转出NEW。在浏览器查询合约或收款地址，余额正确，可惜没有交易记录。建议二地址均增加交易记录，方便双方各自查询交易记录。

3、目前操作基于代码，使用者肯定小众。建议下步升级改进如合伙节点一样傻瓜操作，才好推广使用。

**Comment by VieYang** [comment]
* 关于1和3，后续会考虑整合到APP中增加易用性；
* 关于2，您可以在Newton区块链浏览器中查看，链接 https://explorer.newtonproject.org/contracts
